[FEAT] 운동 리스트 조회 API 구현 (#9)
NOW-SOPT-APP3-PlanFit/PlanFit-SERVER pull request #10
Opened 2024-05-14 14:16 UTC by chaewonni

# 🔥*Pull requests*

## ⛳️ **작업한 브랜치**
- Resolved: #9 

## 👷 **작업한 내용**
- 운동 순서 필드(seq)를 Exercise에서 Routine으로 이동
- Exercise repository, service 구현
- 운동리스트 조회 API 구현
- userId 가 null이거나 1이 아닌 경우 BAD_REQUEST 에러 발생

![image](https://github.com/NOW-SOPT-APP3-PlanFit/PlanFit-SERVER/assets/113420297/a6101608-f411-4df1-84e6-d57703d743ae)

## 🚨 참고 사항
https://github.com/NOW-SOPT-APP3-PlanFit/PlanFit-SERVER/blob/4210554f9f61326d53aeb0158d9fe5c76fc95238/planfit/src/main/java/com/planfit/server/controller/ExerciseController.java#L30-L33

운동리스트 조회 시 BAD_REQUEST가 일어날만한 것은 userId가 잘못 들어오는 경우라고 생각했는데, 에러 메세지도 각각하기로 했기 때문에 일단  EXERCISE_BAD_REQUEST(HttpStatus.BAD_REQUEST.value(), "운동리스트 조회에 실패했습니다.") 를 추가해주었습니다..!

근데 userId가 잘못 들어온건데 잘못된 userId 입니다. 이렇게 에러 메세지를 출력하지 않고  단순히 "message": "운동리스트 조회에 실패했습니다." 이렇게 하는 게 맞는 건지 잘 모르겠습니당...!

2024-05-14 15:25 UTC, jinkonu requested changes
고생하셨습니다~~
리뷰 참고하셔서 수정 부탁드리겠습니다 🥹🥹

2024-05-14 15:25 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/dto/request/ExerciseFindAllDto.java
> +public record ExerciseFindAllDto(
개인적으로 `Find`라는 이름보다는
`Get`이라는 HTTP 메서드에 대응해서 작성해주셨으면 좋겠습니다 !!

2024-05-14 15:25 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/exception/BusinessException.java
> +public class BusinessException extends RuntimeException {
`BusinessException` 대신에
저희 서비스 이름인 `PlanfitException`으로 바꿔주세요 !!

2024-05-14 15:25 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
> +    public ResponseEntity<BaseResponse<?>> exercisesList(@RequestHeader(required = false) Long userId) {
회원 개인의 운동 리스트를 조회한다면
`required` 값은 `true`가 되지 않을까요..?

2024-05-14 15:25 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
> +        }
`userId`에 대한 값 검증은 컨트롤러가 아닌
서비스 계층에서 하는 것이 좋을 것 같습니다 !!
(제가 회원 측을 담당하고 있으니 이 부분은 UserService에서 검증하겠습니다~~)

2024-05-14 15:25 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
> +        responseData.put("exercises", exercises);
`Map` 구조를 추가하지 않더라도
`exercises`라는 리스트 타입 이름을 참고하여
Json의 key 이름을 설정해줄 수도 있을 것 같습니다.
확인해보시고, 만약 그렇다면 `Map` 관련 코드는 지워주시면 좋을 것 같습니다~~~

2024-05-14 15:25 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
> +
만약 운동 리스트 조회에 실패할 이유가
회원 아이디가 존재하지 않기 때문이라면
`USER_NOT_FOUND`라는 에러 메시지를 활용하는 것이 나을 것 같습니다!

추후에 제가 추가하겠습니다!!
참고로, `ExerciseController`에서 예외를 던지면서 이 메시지를 쓰고 있기 때문에
그 부분과 결합해서 함께 생각해주시면 좋을 것 같습니다

2024-05-14 15:25 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/common/GlobalExceptionHandler.java
> +    }
이 부분도 예외 관련한 코멘트와 마찬가지로
NotFoundException에 대한 핸들러를 추가하겠습니다~~

우선은 두시고,
후에 잘못된 요청이 주 원인인 예외를 잡고자 할 때
이 핸들러 메서드를 활용하면 될 것 같네요

2024-05-14 15:49 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/exception/BusinessException.java
> +public class BusinessException extends RuntimeException {
수정했습니다!!

2024-05-14 15:53 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/dto/request/ExerciseFindAllDto.java
> +public record ExerciseFindAllDto(
GetAllExercisesDto로 변경했습니다!

2024-05-14 15:56 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
> +    public ResponseEntity<BaseResponse<?>> exercisesList(@RequestHeader(required = false) Long userId) {
아 required=false를 해주었던 이유가 

@RequestHeader Long userId 애노테이션이 required=true (기본값) 설정이므로, 헤더가 누락된 경우 Spring 자체에서 자동으로 400 Bad Request 오류를 반환해주는데. 이때, 사용자 정의 오류 메시지가 아닌 Spring의 기본 오류 형식이 반환된다고 해서

userId값이 null일 경우에 

``` json
{
    "status": 400,
    "message": "운동리스트 조회에 실패했습니다."
}
```

이 응답을 출력해주기 위함이었는데요...!!

근데 USER_NOT_FOUND로 처리해주기로 했으니 그냥 기본값으로 바꾸겠습니다!!

2024-05-14 15:57 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
> +        }
그럼 그냥 여기는 지우면 될까요!?

2024-05-14 16:03 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/common/GlobalExceptionHandler.java
> +    }
넹 알겠습니다!!

2024-05-14 16:14 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/dto/request/ExerciseFindAllDto.java
> +public record ExerciseFindAllDto(
도메인 메서드 요청/응답 순으로 작성하는게 좋을 것 같아서
`ExerciseGetAllResponse`로 부탁드려요!!

2024-05-14 16:14 UTC, jinkonu commented on planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
> +    public ResponseEntity<BaseResponse<?>> exercisesList(@RequestHeader(required = false) Long userId) {
헐 좋은 사실 배우고 갑니다 ㅎㅎ

2024-05-14 16:17 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/dto/request/ExerciseFindAllDto.java
> +public record ExerciseFindAllDto(
헉 알겠습니다!! 수정했습니다!

2024-05-15 06:38 UTC, sjk4618 approved these changes
수고하셨습니다!

2024-05-15 06:38 UTC, sjk4618 commented on planfit/src/main/java/com/planfit/server/service/ExerciseService.java
> +    @Transactional(readOnly = true)
@Transactional(readOnly = true)
이거를 Service에 달아주는 것이 좋다고 합니다!!
https://hungseong.tistory.com/74

2024-05-15 11:35 UTC, jinkonu commented
LGTM!!
수고하셨어요!!

2024-05-15 11:41 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
> +        responseData.put("exercises", exercises);
넵!! 수정했습니다~!!

2024-05-15 11:44 UTC, chaewonni commented on planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
> +
넹 감사합니다!!!

2024-05-15 11:50 UTC, jinkonu approved these changes

2024-05-15 12:19 UTC, merged